# Generated by Django 5.2.3 on 2025-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('monthly', 'Monthly Summary'), ('yearly', 'Yearly Summary'), ('category', 'Category Breakdown')], max_length=50),
        ),
    ]
