# Generated by Django 5.2.3 on 2025-06-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_alter_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
